### ISSUE TITLE
Code in master does not build

### ISSUE THREAD

**Issue by liuyifan-eric** [uchicago-cs/chiventure#354]
URGENT! The current code in master does not build. Need to be fixed! 
It also breaks all the CI of other PRs.
This is the error info when trying to build
```
make -C ./src/wdl/
make[1]: Entering directory '/media/sf_ucvm/cmsc22000/cmsc22000_group_projects/chiventure/src/wdl'
gcc -fPIC -Wall -Wextra -O2 -g -I./include/ -I../libobj/include/ -I../game-state/include/ -I../action_management/include/ -I../common/include/   -c -o src/parse.o src/parse.c
In file included from ../action_management/include/actionmanagement.h:8:0,
                 from ./include/validate.h:9,
                 from ./include/parse.h:8,
                 from src/parse.c:5:
../common/include/ctx.h:12:20: fatal error: ui_ctx.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'src/parse.o' failed
make[1]: *** [src/parse.o] Error 1
make[1]: Leaving directory '/media/sf_ucvm/cmsc22000/cmsc22000_group_projects/chiventure/src/wdl'
Makefile:30: recipe for target 'src/wdl/wdl.a' failed
make: *** [src/wdl/wdl.a] Error 2
```

**Comment by omorkved** [comment]
What was the most recent thing merged to master? our code was building an hour ago and a few hours ago when the most recent ui code was pushed... no idea why it can't find ui_ctx.h anymore. ideas? I've been checking makefiles...

**Comment by liuyifan-eric** [comment]
Trying to use bisect on master to find which merge/commit breaks the build

**Comment by Gestalt-R** [comment]
#308

**Comment by liuyifan-eric** [comment]
Yes. Git bisect also gives
`ffe411f068cf8ef114c2ef7632a804349527bfa6 is the first bad commit`
So it should be PR #308 , although it passed CI, which is weird.

**Comment by jessxia** [comment]
Included all other team directories in WDL and AM Makefiles
branch: build-fix

**Comment by liuyifan-eric** [comment]
Closing comment:
Bug fixed. Code in master can build now.
Content: included all other team directories in WDL and AM Makefiles

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
